-- DO NOT DELETE --
-- DO NOT DELETE --
-- DO NOT DELETE --
INSERT INTO role_permissions(ROLE, permission)
    VALUES ('owner', 'chests.insert'),
('collaborator', 'chests.insert'),
('viewer', 'chests.insert'),
('owner', 'chests.select'),
('collaborator', 'chests.select'),
('viewer', 'chests.select'),
('owner', 'chests.update'),
('owner', 'chests.delete'),
('owner', 'collections.insert'),
('collaborator', 'collections.insert'),
('owner', 'collections.select'),
('collaborator', 'collections.select'),
('viewer', 'collections.select'),
('owner', 'collections.update'),
('collaborator', 'collections.update'),
('owner', 'collections.delete'),
('collaborator', 'collections.delete'),
('owner', 'people.insert'),
('collaborator', 'people.insert'),
('owner', 'people.select'),
('collaborator', 'people.select'),
('viewer', 'people.select'),
('owner', 'people.update'),
('collaborator', 'people.update'),
('owner', 'people.delete'),
('collaborator', 'people.delete'),
('owner', 'person_avatar_urls.insert'),
('collaborator', 'person_avatar_urls.insert'),
('owner', 'person_avatar_urls.select'),
('collaborator', 'person_avatar_urls.select'),
('viewer', 'person_avatar_urls.select'),
('owner', 'person_avatar_urls.update'),
('collaborator', 'person_avatar_urls.update'),
('owner', 'person_avatar_urls.delete'),
('collaborator', 'person_avatar_urls.delete'),
('owner', 'gems.insert'),
('collaborator', 'gems.insert'),
('owner', 'gems.select'),
('collaborator', 'gems.select'),
('viewer', 'gems.select'),
('owner', 'gems.update'),
('collaborator', 'gems.update'),
('owner', 'gems.delete'),
('collaborator', 'gems.delete'),
('owner', 'lines.insert'),
('collaborator', 'lines.insert'),
('owner', 'lines.select'),
('collaborator', 'lines.select'),
('viewer', 'lines.select'),
('owner', 'lines.update'),
('collaborator', 'lines.update'),
('owner', 'lines.delete'),
('collaborator', 'lines.delete'),
('owner', 'invitations.insert'),
('owner', 'invitations.select'),
('owner', 'invitations.update'),
('owner', 'invitations.delete');

