CREATE TABLE IF NOT EXISTS "public"."people"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nickname" "text" NOT NULL,
    "date_of_birth" date NOT NULL,
    "chest_id" "uuid" NOT NULL
);

ALTER TABLE ONLY "public"."people"
    ADD CONSTRAINT "connections_pkey" PRIMARY KEY ("id");
