name: code-check
description: code-check

runs:
  using: "composite"

  steps:
    - name: 📦 Install Dependencies
      shell: bash
      run: |
        flutter pub global activate melos
        flutter pub global activate combine_coverage
        flutter pub global activate remove_from_coverage
        melos clean
        melos bootstrap
        melos update_settings --no-select

    - name: ✨ Check Formatting
      shell: bash
      run: melos format

    - name: 🕵️ Analyze
      shell: bash
      run: melos analyze

    - name: 🧪 Run Tests
      shell: bash
      run: melos run test --no-select

    - name: 📊 Check Code Coverage
      shell: bash
      run: melos run check_coverage
