name: cperson_repository

environment:
  sdk: ^3.11.0
  
resolution: workspace

dependencies:
  bobs_jobs: any
  ccore:
  cdatabase_client:
  cplatform_client:
  cstorage_client:
  equatable: ^2.0.5
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_beautifier: ^3.0.0
  very_good_analysis: ^10.2.0
