name: staging
description: staging

runs:
  using: "composite"

  steps:
    - name: 🏗️ Build Staging App
      shell: bash
      run: melos build_staging -- --dart-define=SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}
