name: cpub

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  bobs_jobs: ^0.0.1-dev.2
  dart_jsonwebtoken: ^2.14.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.19.0
  meta: ^1.12.0
  pinput: ^5.0.0
  share_plus: ^9.0.0
  signed_spacing_flex: ^1.1.0
  supabase: ^2.1.3
  supabase_flutter: ^2.5.3
  url_launcher: ^6.2.6

dev_dependencies:
  cpub_dev:
