name: cplatform_repository

environment:
  sdk: ^3.11.0
  
resolution: workspace

dependencies:
  bobs_jobs: any
  ccore:
  cplatform_client:
  image: ^4.5.4

dev_dependencies:
  very_good_analysis: ^10.2.0
