name: chuckle_chest
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cpub:
  flutter:
    sdk: flutter

dev_dependencies:
  cpub_dev:

flutter:
  uses-material-design: true
