name: chuckle_chest
description: "A new Flutter project."
publish_to: "none"
version: 0.12.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  auto_route: ^8.1.4
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  bobs_jobs: ^0.0.1-dev.4
  cauth_client:
  cauth_repository:
  cchest_repository:
  ccore:
  cdatabase_client:
  cgem_repository:
  cperson_repository:
  cplatform_client:
  crop_your_image: ^1.1.0
  cstorage_client:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  meta: ^1.15.0
  pinput: ^5.0.0
  signed_spacing_flex: ^1.1.0
  supabase_flutter: ^2.6.0
  transparent_image: ^2.0.1
  url_launcher: ^6.3.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_beautifier: ^1.1.0

flutter:
  uses-material-design: true
