name: chuckle_chest
description: "A new Flutter project."
publish_to: "none"
version: 0.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cauth_client:
  cauth_repository:
  ccore:
  cgem_client:
  cgem_repository:
  cplatform_client:
  cpub:
  csupabase_client:
  flutter:
    sdk: flutter

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  cpub_dev:

flutter:
  uses-material-design: true
