name: cgem_repository

environment:
  sdk: ^3.11.0
  
resolution: workspace

dependencies:
  bobs_jobs: any
  ccore:
  cdatabase_client:
  cperson_repository: # Only used for the CPerson model.
  cplatform_client:
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_beautifier: ^3.0.0
  very_good_analysis: ^7.0.0
