name: production
description: production

runs:
  using: "composite"

  steps:
    - name: 🏗️ Build Production App
      shell: bash
      run: melos build_production -- --dart-define=SUPABASE_PROJECT_URL=${{ env.SUPABASE_PROJECT_URL }} --dart-define=SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}

    - name: ⬆️ Update Website
      shell: bash
      run: melos update_website

    - name: 🔧 Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: 📤 Upload Production App
      uses: actions/upload-pages-artifact@v3
      with:
        path: "./website/public"

    - name: ⚡️ Setup Supabase
      uses: supabase/setup-cli@v1
      with:
        version: latest

    - name: 🗃️ Push Database Changes
      shell: bash
      run: |
        supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
        supabase db push

    - name: 🚀 Deploy Production Website and App
      id: deployment
      uses: actions/deploy-pages@v4
