CREATE TABLE IF NOT EXISTS "public"."lines"(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "text" "text" NOT NULL,
    "gem_id" "uuid" NOT NULL,
    "chest_id" "uuid" NOT NULL,
    "person_id" bigint
);

ALTER TABLE ONLY "public"."lines"
    ADD CONSTRAINT "lines_pkey" PRIMARY KEY ("id");
