name: ccore

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_beautifier: ^1.1.0
  very_good_analysis: ^7.0.0
