name: cauth_repository

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bobs_jobs: ^0.0.1-dev.16
  cauth_client:
  ccore:
  equatable: ^2.0.5
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test_beautifier: ^1.1.0
  very_good_analysis: ^6.0.0
